former_base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : ['left_wheel_joint']
  right_wheel : ['right_wheel_joint']
  publish_rate: 50.0  
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter
  wheel_separation: 0.305
  wheel_radius    : 0.085

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 
  wheel_radius_multiplier    : 1.1

  # Velocity commands timeout [s]
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: base_link

  # Odom frame id
  odom_frame_id: odom

  enable_odom_tf: false

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0  # m/s
      min_velocity           : -1.0 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.8  # m/s^2
      min_acceleration       : -0.8 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0  # rad/s
      min_velocity           : -2.0 # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.6  # rad/s^2
      min_acceleration       : -1.6 # rad/s^2


former_joint_state_controller:
  type: joint_state_controller/JointStateController 
  publish_rate: 50.0


twist_mux:
  topics:
  - name    : Joystick
    topic   : teleop/cmd_vel
    timeout : 0.5
    priority: 100

  - name    : Navigation
    topic   : move_base/cmd_vel
    timeout : 0.5
    priority: 50

  - name    : Docking
    topic   : dock/cmd_vel
    timeout : 0.5
    priority: 20

  - name    : External
    topic   : cmd_vel
    timeout : 0.5
    priority: 10

  locks:
  - name    : Emergency Stop Switch
    topic   : emergency_stop
    timeout : 0.0    
    priority: 255


ekf_localization_node:
  frequency: 50
  sensor_timeout: 0.1

  two_d_mode: true
  publish_tf: true
  publish_acceleration: false
  print_diagnostics: false
  debug: false

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  odom0: /former_base_controller/odom
  odom0_config: [true, true, false,
                 false, false, true,
                 true, false, false,
                 false, false, true,
                 false, false, false]
  odom0_differential: false
  odom0_relative: false

  imu0: /imu/data
  imu0_config: [false, false, false,
                false, false, false,
                false, false, false,
                false, false, true,
                true, false, false]
  imu0_differential: false
  imu0_relative: false
  imu0_remove_gravitational_acceleration: true
